### ISSUE TITLE
Fail2Ban firewall bans the relay server

### ISSUE THREAD

**Issue by abhin4v** [g3rv4/FakeRelay#1]
The Fail2Ban firewall on the VPS on which I run a Mastodon server is configured to reject HTTP requests without the User-agent header. The HTTP call made from your relay to push the updates is done without this header, and the firewall bans the relay IP. I expect many server firewalls to have this configuration.
Please add the User-agent header to the HTTP calls from the relay to fix this issue. Any header value will do.

**Comment by g3rv4** [comment]
This has been deployed, thanks for raising it!
