### ISSUE TITLE
Rejected Announce activity

### ISSUE THREAD

**Issue by bahuma20** [g3rv4/FakeRelay#13]
I am trying to host my own FakeRelay to use it with my self-hosted Mastodon instance, but the posts don't appear.

This is my configuration:
```json
{
  "GrafanaDataSourceId":null,
  "GrafanaKey":null,
  "GrafanaHost":null,
  "HomeRedirect":null,
  "Host":"fakerelay.noitl.space",
  "PrivateKey":"[redacted]",
  "PublicKey":"[redacted]"
```

In Mastodon i have set-up the relay with the URL /inbox:
![image](https://github.com/g3rv4/FakeRelay/assets/5746121/ae682f7f-88f6-4a2d-a767-130d5422f488)

I have also added the instance via cli:
![image](https://github.com/g3rv4/FakeRelay/assets/5746121/c95e858a-a2ad-4c1b-b2f1-9ebb121a43e5)

Then i used curl to import a post and get OK back:
![image](https://github.com/g3rv4/FakeRelay/assets/5746121/7dc54914-ceea-4fe3-82de-6d43dd54b8c0)

But now i don't see the post in the federated timeline or in the hashtag search.

In the Mastodon logs i saw this message:
```
Rejected Announce activity https://fakerelay.noitl.space/activities/d51239c7-7f0d-49d5-804e-e003b929240a from https://fakerelay.noitl.space/actor
```

What did i configure wrong? Does anybody have any idea?

**Comment by g3rv4** [comment]
the status url is wrong :) you can't use the toot's url, you have to use its id instead: `https://mastodon.social/users/the_bandito0/statuses/110549834654794617`

try that and let me know :)

**Comment by g3rv4** [comment]
also, you can find the id for that toot by adding `.json` to the url, I got it from `https://mastodon.social/@the_bandito0/110549834654794617.json`

**Comment by g3rv4** [comment]
and FakeRelay returns Ok because that's what it got from your instance :) sorry for the multiple messages

**Comment by bahuma20** [comment]
Ahhh that makes sense...

Now it works and i am ready to configure GetMoar 😄 

Thank you for the quick response and your support 😎 👍
