### ISSUE TITLE
FakeRelay suddenly stopped working here

### ISSUE THREAD

**Issue by Leatherface75** [g3rv4/FakeRelay#15]
FakeRelay stopped working here without any changes and when trying to readd Fakerelay i am getting this in docker container.

> fakerelay-fakerelay-1  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
> fakerelay-fakerelay-1  |       Failed to determine the https port for redirect.
> fakerelay-fakerelay-1  | fail: FakeRelay.Web.Services.QueuedHostedService[0]
> fakerelay-fakerelay-1  |       Error occurred executing workItem.
> fakerelay-fakerelay-1  |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
> fakerelay-fakerelay-1  |        ---> System.TimeoutException: A task was canceled.
> fakerelay-fakerelay-1  |        ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
> fakerelay-fakerelay-1  |          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.SendMessageToInboxAsync(String targetHost, String content) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 45
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.ProcessInstanceFollowAsync(ActivityPubModel request) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 52
> fakerelay-fakerelay-1  |          at FakeRelay.Web.Services.QueuedHostedService.BackgroundProcessing(CancellationToken stoppingToken) in /src/FakeRelay.Web/Services/QueuedHostedService.cs:line 86

**Comment by Leatherface75** [comment]
Any ideas what's wrong?

**Comment by Leatherface75** [comment]
Any ideas what's wrong?
I have tried reconfiguring, reinstalling containers etc nothing helps.

**Comment by g3rv4** [comment]
huh, I don't know... but seeing the background code is rarely hit (only when adding an instance) I'm thinking I'll remove it

**Comment by g3rv4** [comment]
can you try with version  1.0.39?

**Comment by Leatherface75** [comment]
Ok i will try update it and see if it helps.
Strange thing is that it worked earlier.

**Comment by Leatherface75** [comment]
Now i am getting this

> fakerelay-cli-1        | USAGE:
> fakerelay-cli-1        |     FakeRelay.Cli.dll [OPTIONS] <COMMAND>
> fakerelay-cli-1        | 
> fakerelay-cli-1        | OPTIONS:
> fakerelay-cli-1        |     -h, --help       Prints help information   
> fakerelay-cli-1        |     -v, --version    Prints version information
> fakerelay-cli-1        | 
> fakerelay-cli-1        | COMMANDS:
> fakerelay-cli-1        |     instance                                                          
> fakerelay-cli-1        |     list-instances             Lists the hosts and their keys         
> fakerelay-cli-1        |     config <FAKERELAY_HOST>    Initializes the FakeRelay configuration
> fakerelay-cli-1 exited with code 0
> fakerelay-fakerelay-1  | warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
> fakerelay-fakerelay-1  |       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
> fakerelay-fakerelay-1  | info: Microsoft.Hosting.Lifetime[14]
> fakerelay-fakerelay-1  |       Now listening on: http://[::]:5000
> fakerelay-fakerelay-1  | info: Microsoft.Hosting.Lifetime[0]
> fakerelay-fakerelay-1  |       Application started. Press Ctrl+C to shut down.
> fakerelay-fakerelay-1  | info: Microsoft.Hosting.Lifetime[0]
> fakerelay-fakerelay-1  |       Hosting environment: Production
> fakerelay-fakerelay-1  | info: Microsoft.Hosting.Lifetime[0]
> fakerelay-fakerelay-1  |       Content root path: /app/
> fakerelay-fakerelay-1  | warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
> fakerelay-fakerelay-1  |       Failed to determine the https port for redirect.
> fakerelay-fakerelay-1  | Exception The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing. when connecting to xxxxxxxxxx
> fakerelay-fakerelay-1  | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
> fakerelay-fakerelay-1  |       An unhandled exception has occurred while executing the request.
> fakerelay-fakerelay-1  |       System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
> fakerelay-fakerelay-1  |        ---> System.TimeoutException: A task was canceled.
> fakerelay-fakerelay-1  |        ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
> fakerelay-fakerelay-1  |          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.SendMessageToInboxAsync(String targetHost, String content) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 47
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.ProcessInstanceFollowAsync(ActivityPubModel request) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 60
> fakerelay-fakerelay-1  |          at FakeRelay.Web.Controllers.AcitivityPubController.Inbox(ActivityPubModel model) in /src/FakeRelay.Web/Controllers/AcitivityPubController.cs:line 19
> fakerelay-fakerelay-1  |          at lambda_method4(Closure , Object )
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
> fakerelay-fakerelay-1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
> fakerelay-fakerelay-1  |       Connection id "0HMRTJ1VHCIAV", Request id "0HMRTJ1VHCIAV:00000002": An unhandled exception was thrown by the application.
> fakerelay-fakerelay-1  |       System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
> fakerelay-fakerelay-1  |        ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
> fakerelay-fakerelay-1  |        ---> System.TimeoutException: A task was canceled.
> fakerelay-fakerelay-1  |        ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
> fakerelay-fakerelay-1  |          at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
> fakerelay-fakerelay-1  |          at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.SendMessageToInboxAsync(String targetHost, String content) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 47
> fakerelay-fakerelay-1  |          at FakeRelay.Core.Helpers.MastodonHelper.ProcessInstanceFollowAsync(ActivityPubModel request) in /src/FakeRelay.Core/Helpers/MastodonHelper.cs:line 60
> fakerelay-fakerelay-1  |          at FakeRelay.Web.Controllers.AcitivityPubController.Inbox(ActivityPubModel model) in /src/FakeRelay.Web/Controllers/AcitivityPubController.cs:line 19
> fakerelay-fakerelay-1  |          at lambda_method4(Closure , Object )
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
> fakerelay-fakerelay-1  |          --- End of inner exception stack trace ---
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
> fakerelay-fakerelay-1  |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by Leatherface75** [comment]
Tried reinstall docker and now maybe it works again.
Still getting this Redirection error but it seems to send URL's now.

**Comment by Leatherface75** [comment]
Closing this for now.
Opening it again if problems continues.
