### ISSUE TITLE
arm64 docker images

### ISSUE THREAD

**Issue by linksu** [g3rv4/FakeRelay#6]
Would it be possible to create images for arm64 arch as well?

**Comment by g3rv4** [comment]
sure! I added that on 20befd3d9e308137c45440eb5ba7baf52450820f. Can you give it a try using the image `ghcr.io/g3rv4/fakerelay:latest-arm64v8`? or if you want to use a particular version (starting on  1.0.21) you can use  `ghcr.io/g3rv4/fakerelay:1.0.21-arm64v8`

**Comment by g3rv4** [comment]
I'm closing this, but if you find any issues with it I'll reopen it :)

**Comment by linksu** [comment]
Thanks! 
I tried with the `ghcr.io/g3rv4/fakerelay:latest-arm64v8`, and it gives this error on the docker-compose run:
`/bin/cli: line 1: syntax error: unexpected "("`

**Comment by g3rv4** [comment]
how are you running it? I'd love to try yo reproduce it. Can you get me some details? what distro?

**Comment by linksu** [comment]
Sure! It's a fresh install of the latest DietPi on PINE A64, a modified Debian Bullseye ARMv8 image. (https://dietpi.com/)

Docker is installed via `curl -fsSL https://get.docker.com -o get-docker.sh` && `sudo sh get-docker.sh`
docker-compose was installed via apt (from bullseye/main arm64 packages).

I now upgraded docker-compose to version 1.27.4 (from bullseye/backports) and now it runs a bit further:
```
Creating fakerelay_cli_run ... done
/bin/cli: line 1: syntax error: unexpected "("
```

**Comment by g3rv4** [comment]
good news! I was able to repro this on an arm EC2 instance... I'll keep on troubleshooting :)

**Comment by linksu** [comment]
Thanks for the update, that’s good news. :)
I was wondering does dotnet need an arm image as well? Just a thought that came to mind.

**Comment by g3rv4** [comment]
yes, I'm using the ms provided arm image. I think there's something funky with the bash script I have

**Comment by g3rv4** [comment]
can you try with  `ghcr.io/g3rv4/fakerelay:1.0.22-arm64v8`?

**Comment by linksu** [comment]
Seems to work! No errors this time and the commands are working.
I’ll configure the remaining bits tomorrow and setup GetMoarFediverse as well. :)

Thanks for the help (and for sharing this project)!

**Comment by g3rv4** [comment]
awesome, all I had to do was to build on a matching image: https://github.com/g3rv4/FakeRelay/commit/f3ec35c8028599a5a06b385788357e0dc6f75c5e

**Comment by linksu** [comment]
I now have configured reverse proxy via nginx and generated a key for my instance. 

The container is up and running, but nginx is giving error 502 (Bad Gateway): 
`2022/12/20 10:43:00 [error] 273424#273424: *173 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 88.86.156.223, server: relayslf.leetgroup.org, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:5000/", host: "relayslf.leetgroup.org"`

docker logs:
```
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {148bb711-7708-4861-bf92-6b2cc97bb578} may be persisted to storage in unencrypted form.
info: FakeRelay.Web.Services.QueuedHostedService[0]
      Queued Hosted Service is running.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app/
```
config.json contents:
`{"HomeRedirect":null,"Host":"relayslf.leetgroup.org","PrivateKey":"-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----","PublicKey":"-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----"}`

**Comment by g3rv4** [comment]
given the docker logs, it seems like the app isn't receiving any traffic.

what's on your `docker-compose.yml`? and is nginx running on the host? or also as a docker container? what does the nginx file look like?

**Comment by linksu** [comment]
You were right, it was a firewalling issue. 
I disabled the firewall for a sec and immediately FakeRelay responded correctly.
I'm using Shorewall and I had the default bridge _docker0_ interface configured, but I was missing the correct configs for other _br-*_ interfaces in Shorewall.

Thanks again! :)
