### ISSUE TITLE
Can't run on Oracle Cloud ARM instance

### ISSUE THREAD

**Issue by lnlyssg** [g3rv4/FakeRelay#8]
I think this may be similar to #6... I'm trying to run this using Docker on an Oracle ARM image using their free tier but get `exec /app/entrypoint.sh: exec format error` in the logs as soon as I start it

**Comment by g3rv4** [comment]
hi there! what does your docker-compose.yml look like?

**Comment by lnlyssg** [comment]
It's identical to the one in the readme but with the volumes set to `/opt/fakerelay:/data`

**Comment by g3rv4** [comment]
ah, if it's identical that means you're using the wrong image.

Instead of :latest, try with :1.0.22-arm64v8

**Comment by g3rv4** [comment]
or you can use :latest-arm64v8 if you prefer not to specify the version

**Comment by lnlyssg** [comment]
Ah super, I can now start it! Thanks for the pointers.
